name: papersready_sa
description: PapersReady SA - Private Community Helper, NOT SASSA. We help draft docs after rejection.
publish_to: 'none'
version: 1.0.9+9

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.5
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  pdf: ^3.10.7
  share_plus: ^7.2.1
  http: ^1.2.0

flutter:
  uses-material-design: true
