import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfService {
  Future<String> generateAppealLetter({required String idNumber, required String phoneNumber, required String town, required String language, required String momoTxId, required bool verified}) async {
    final pdf = pw.Document();
    pdf.addPage(
      pw.Page(
        build: (context) => pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          pw.Text('PAPERSREADY SA - SASSA SRD APPEAL LETTER', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 20),
          pw.Text('To: SASSA Appeals Department'),
          pw.Text('Town: $town'),
          pw.Text('Date: ${DateTime.now().toString().split(' ')[0]}'),
          pw.SizedBox(height: 15),
          pw.Text('ID Number: ${idNumber.substring(0,6)}****** (cleared after generation)'),
          pw.Text('Phone: $phoneNumber'),
          pw.Text('MoMo Transaction ID: $momoTxId - Verified: $verified'),
          pw.SizedBox(height: 15),
          pw.Text('Dear Sir/Madam,', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 10),
          pw.Text('I hereby appeal my SASSA SRD R370 grant that was declined. I declare that my income is below R624 and I have no other income source. Please re-evaluate my application. I attach this appeal as required by SASSA Act.'),
          pw.SizedBox(height: 20),
          pw.Text('I understand this letter is generated in English as required by SASSA national system.'),
          pw.SizedBox(height: 30),
          pw.Text('Yours faithfully,'),
          pw.Text('Applicant from $town'),
          pw.SizedBox(height: 40),
          pw.Text('Generated by PapersReady SA - 24/7 - R20 - WhatsApp Delivery - Two-way verification passed', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
        ]),
      ),
    );
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/appeal_$town.pdf');
    await file.writeAsBytes(await pdf.save());
    return file.path;
  }
}
